frontend/controllers/PayController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use backend\models\Pay;
use frontend\models\rebate\PaymentChangeForm;
use frontend\models\rebate\OutputForm;
use common\models\rebate\Output;
use yii\web\NotFoundHttpException;
use common\models\User;
use frontend\models\rebate\UserPay;

/**
 * Site controller
 */
class PayController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function init()
    {
        parent::init();
        $this->layout = 'vpluse';
    }

    /**
     * Lists all User Payments.
     * @return mixed
     */
    public function actionPaymentDetails()
    {
        $payments = Pay::find()->where('status=1')->joinWith([
            'userPays' => function ($query) {
                $query->onCondition(['user_pay.user_id' => Yii::$app->user->id]);
            },
        ])->all();

        $payments_details = [];
        foreach ($payments as $key => $payment) {
            $payments_details[$key]['id'] = $payment->id;
            $payments_details[$key]['name'] = $payment->name;
            $payments_details[$key]['value'] = $payment->userPays ? $payment->userPays[0]->value : '-';
        }

        return $this->render('payment_details', [
            'payments_details' => $payments_details,
        ]);
    }

    /**
     * Change User Payments.
     * @param integer $pay_id
     * @return mixed
     */
    //change-payment-detail
    public function actionChangePaymentDetail($pay_id)
    {
        $user = $this->findModel(Yii::$app->user->id);
        $pay = Pay::find()->where('pay.id='. $pay_id)->joinWith([
            'userPays' => function ($query) {
                $query->onCondition(['user_pay.user_id' => Yii::$app->user->id]);
            },
        ])->one();

        $model = new PaymentChangeForm($user, $pay);

        if ($model->load(Yii::$app->request->post()) && $model->changePayment()) {
            Yii::$app->session->setFlash('success', 'Реквизиты успешно сохранены.');

            return $this->redirect(['payment-details']);
        } else {
            return $this->render('payment_change', [
                'model' => $model,
            ]);
        }

    }

    /**
     * Output money
     * @return mixed
     */
    public function actionOutput()
    {
        $service = isset($_SESSION['service']) ? $_SESSION['service'] : null;
        switch ($service) {
            case 'rebate' :
                    $service_id = 1;
                break;
            case 'vps' :
                    $service_id = 2;
                break;
            case 'bot' :
                    $service_id = 3;
                break;
            default : $service_id = 0;
        }

        $model = new OutputForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $output_model = new Output();
            $output_model->id_user = Yii::$app->user->id;
            $output_model->amount = $model->credit;
            $payData = $model->paymentData();
            $output_model->payment_detail = $payData['payment_detail'];
            $output_model->payment = $payData['payment'];
            $output_model->service_id = $service_id;

            if ($output_model->save()) {
                $params =[
                    'id' => $output_model->id,
                    'amount' => $output_model->amount,
                    'payment_detail' => $output_model->payment_detail,
                ];
                //Уведомление для админа
                User::sendMailToAdmin(10, $params);
                //Уведомление для пользователя idUser
                $output_model->idUser->sendMail(11, $params);
                Yii::$app->session->setFlash('success', 'Заявка на вывод средств успешно отправлена');
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось создать заявку');
            }
        }

        return $this->render('output', [
            'model' => $model,
        ]);

    }

    /**
     * Check user payment detail
     */
    public function actionGetPayment()
    {
        if(!Yii::$app->request->isAjax) {
            exit('go home!');
        }
        $user_payment_detail = '';
        if($post = Yii::$app->request->post()) {
            if(isset($post['pay_id'])) {
                $user_payment_detail = UserPay::find()
                    ->where(['user_id'=> Yii::$app->user->id, 'pay_id' => $post['pay_id']])
                    ->one();
            }
            if($user_payment_detail) {
                exit($user_payment_detail->value);
            }
        }
        exit($user_payment_detail);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/vpluse/bot_left.php
<?php
use frontend\widgets\SectionMenuWidget;
?>
<div class="sidebar">
    <ul class="sidebar__nav">
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-support" href="/rebate/default/support">
                <span class="sidebar__title">Техподдержка</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-profile" href="/rebate/profile">
                <span class="sidebar__title">Мой профиль</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance" href="#?">
                <span class="sidebar__title">Баланс</span>
            </a>
        </li>
    </ul>
    <a class="show-menu" href="#?">
        <span class="show-menu__ico"></span>
        <span class="show-menu__title">свернуть</span>
    </a>
</div>

frontend/views/vpluse/head.php
<?php
$avatar = Yii::$app->params['avatarURL'] . 'no_photo.jpg';
if(Yii::$app->user->identity->avatar && file_exists(Yii::getAlias("@avatar") . Yii::$app->user->identity->avatar)) {
    $avatar = Yii::$app->params['avatarURL'] . Yii::$app->user->identity->avatar;
}
$service = isset($_SESSION['service']) ? $_SESSION['service'] : null;
?>
<header class="header">
    <div class="block__container">
        <div class="logo">
            <a class="logo__wrapper" href="/">
                <img class="logo__img" src="/img/logo.png" alt="logo">
                <img class="logo__mob" src="/img/logo_mob.png" alt="logo">
            </a>
        </div>
        <div class="authorization">
            <a href="/site/logout" class="logout btn_main">Выйти</a>
        </div>
        <div class="user">
            <div class="user__info user__info_height">
                <div class="user__photo">
                    <img src="<?= $avatar  ?>" alt="user_photo">
                </div>
                <div class="user__description">
                    <span class="user__title"><?= Yii::$app->user->identity->first_name ?> <?= Yii::$app->user->identity->last_name ?></span>
                    <span class="user__subtitle"><?= Yii::$app->user->identity->username ?></span>
                </div>
            </div>
            <div class="user__info user__info_margin">
                <div class="user__ico">
                    <img src="/img/balance.png" alt="balance_photo">
                </div>
                <div class="user__description">
                    <span class="user__title"><?= $service != 'partner' ? 'Баланс' : 'Партнерский баланс' ?></span>
                    <span class="user__subtitle"><?= $service != 'partner' ? Yii::$app->user->identity->balance : Yii::$app->user->identity->balance_partner ?>$</span>
                </div>
            </div>
        </div>
    </div>
</header>

frontend/views/vpluse/partner_left.php
<?php
use yii\helpers\Url;

$current_action = Yii::$app->controller->action->id;
$current_controller = Yii::$app->controller->id;
$active_balance = '';
if($current_controller == 'pay' || $current_action == 'history') {
    $active_balance = ' active';
}
?>
<div class="sidebar">
    <ul class="sidebar__nav">
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance<?php echo $current_action == 'index' ? ' active-empty' : ''?>" href="/partner">
                <span class="sidebar__title">Промо материалы</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance<?php echo $current_action == 'customers' ? ' active-empty' : ''?>" href="/partner/customers">
                <span class="sidebar__title">Клиенты</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance js-drop<?= $active_balance ?>" href="#?">
                <span class="sidebar__title">Начисления</span>
            </a>
            <ul class="dropdown">
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_action == 'history' ? ' active' : ''?>" href="<?= Url::to(['/partner/history']) ?>">История начислений</a>
                </li>
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_action == 'output' ? ' active' : ''?>" href="<?= Url::to(['/pay/output']) ?>">Вывести средства</a>
                </li>
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_action == 'payment-details' ? ' active' : ''?>" href="<?= Url::to(['/pay/payment-details']) ?>"">Платежные реквизиты</a>
                </li>
            </ul>
        </li>
    </ul>
    <a class="show-menu" href="#?">
        <span class="show-menu__ico"></span>
        <span class="show-menu__title">свернуть</span>
    </a>
</div>

frontend/views/vpluse/rebate_left.php
<?php
use yii\helpers\Url;
use frontend\widgets\SectionMenuWidget;
$current_action = Yii::$app->controller->action->id;
$current_controller = Yii::$app->controller->id;
$active_balance = '';
if($current_controller == 'balance' || $current_controller == 'pay') {
    $active_balance = ' active';
}
//echo '<pre>'; var_dump($current_action); echo '</pre>'; exit;
?>
<div class="sidebar">
    <ul class="sidebar__nav">
        <?= SectionMenuWidget::widget(); ?>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-support<?php echo $current_action == 'support' ? ' active-empty' : ''?>" href="<?= Url::to(['/rebate/default/support']) ?>">
                <span class="sidebar__title">Техподдержка</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-profile<?php echo $current_controller == 'profile' ? ' active-empty' : ''?>" href="<?= Url::to(['/rebate/profile']) ?>">
                <span class="sidebar__title">Мой профиль</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance js-drop<?= $active_balance ?>" href="#?">
                <span class="sidebar__title">Баланс</span>
            </a>
            <ul class="dropdown">
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_controller == 'balance' ? ' active' : ''?>" href="<?= Url::to(['/rebate/balance']) ?>">История операций</a>
                </li>
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_action == 'output' ? ' active' : ''?>" href="<?= Url::to(['/pay/output']) ?>">Вывести средства</a>
                </li>
                <li class="dropdown__row">
                    <a class="dropdown__item<?php echo $current_action == 'payment-details' ? ' active' : ''?>" href="<?= Url::to(['/pay/payment-details']) ?>">Платежные реквизиты</a>
                </li>
            </ul>
        </li>
    </ul>
    <a class="show-menu" href="#?">
        <span class="show-menu__ico"></span>
        <span class="show-menu__title">свернуть</span>
    </a>
</div>

frontend/views/vpluse/right.php
<?php
use frontend\widgets\NewsWidget;
use frontend\widgets\StaticBlockWidget;
use yii\helpers\Url;
?>
<?php
if($ref_back = StaticBlockWidget::widget(['id' => 1])) {
    ?>
    <div class="refback">
        <?= $ref_back ?>
    </div>
    <?php
}
?>
<div class="news">
    <span class="title-block">Наши новости</span>
    <ul class="news__list">
        <?php NewsWidget::begin(); ?>
        <li class="news__item">
            <div class="news__date">:date</div>
            <a class="news__title" href="<?= Url::to(['/site/news', 'id' => 'newsId']) ?>"><span>:title</span></a>
        </li>
        <?php NewsWidget::end(); ?>
    </ul>
</div>

frontend/views/vpluse/vps_left.php
<?php
use frontend\widgets\SectionMenuWidget;
?>
<div class="sidebar">
    <ul class="sidebar__nav">
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-support" href="/rebate/default/support">
                <span class="sidebar__title">Техподдержка</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-profile" href="/rebate/profile">
                <span class="sidebar__title">Мой профиль</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-balance" href="#?">
                <span class="sidebar__title">Баланс</span>
            </a>
        </li>
    </ul>
    <a class="show-menu" href="#?">
        <span class="show-menu__ico"></span>
        <span class="show-menu__title">свернуть</span>
    </a>
</div>