backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\AdminLoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->redirect(['/rebate/output']);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new AdminLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'main-login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'На ваш почтовый ящик была выслана ссылка на сброс пароля.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Неудалось изменить пароль.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль Был сохранен.');

            return $this->goHome();
        }
        $this->layout = 'main-login';

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use common\models\rebate\News;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use yii\data\ActiveDataProvider;


/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['index', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = 'vpluse';
        $service = 'rebate';
        if (isset(Yii::$app->request->queryParams['service'])) {
            $service = Yii::$app->request->queryParams['service'];
        }
        $session = Yii::$app->session;
        $session->set('service', $service);

        $cookies = Yii::$app->request->cookies;
        if ($cookies->get('register') == null) {
            $cookies = Yii::$app->response->cookies;
            $cookies->add(new \yii\web\Cookie([
                'name' => 'register',
                'value' => 'zzz',
                'expire' => time() + 60*60*24*1000,
            ]));
        }

        $this->redirect('/rebate/balance');

        return $this->render('index', ['service' => $service]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays news page.
     *
     * @return mixed
     */
    public function actionNews($id = null)
    {
        if ($id) {

            return $this->render('news-single', [
                'news' => News::findOne($id),
            ]);
        }

        $dataProvider = new ActiveDataProvider([
            'query' => News::find()->orderBy('created_at DESC'),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('news', ['listDataProvider' => $dataProvider]);

    }


    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {

                    return $this->goHome();
                }
            }
        }

        $cookies = Yii::$app->request->cookies;
        if ($cookies->get('register') !== null) {
            $name = 'Регистрация';
            $message = 'Вы уже зарегистрированы на этом сайте.';

            return $this->render('error', [
                'name' => $name,
                'message' => $message
            ]);

        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте почтовый ящик и следуйте инструкциям.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Неудалось изменить пароль.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль Был сохранен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/_list_news.php
<?php
/* @var $model object */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\HtmlPurifier;
?>
<div class="site-news">
    <a href="<?= Url::to(['site/news', 'id' => $model->id]); ?>"><div class="info__title"><?= Html::encode($model->title) ?></div></a>
    <span><?= Yii::$app->formatter->asDate($model->created_at) ?></span>
    <div class="info__text"><?= HtmlPurifier::process(substr($model->content, 0, 550)) . '...' ?></div>
    <hr>
</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        Ошибка, во время обработки запроса.
    </p>
    <p>
        Пожалуйста, свяжитесь с нами, если вы считаете, что это ошибка сервера. Спасибо.
    </p>

</div>

frontend/views/site/head.php
<header class="header">
    <div class="block__container">
        <div class="logo">
            <a class="logo__wrapper" href="/">
                <img class="logo__img" src="/img/logo_zzz.png" alt="logo">
                <img class="logo__mob" src="/img/logo_mob.png" alt="logo">
            </a>
        </div>
        <div class="authorization">
            <a href="/" class="logout btn_main">Вход</a>
        </div>
    </div>
</header>

frontend/views/site/index.php
<?php
/* @var $service string */
?>
<div class="content__section">
    <div class="info">
        <span class="title-block">
            <?php
            switch ($service) {
                case 'rebate' :
                    echo 'Сервис Rebate';
                    break;
                case 'vps' :
                    echo 'Vpluse-vps';
                    break;
                case 'bot' :
                    echo 'Vpluse-bot';
                    break;
                default : echo 'Сервис не выбран';
            }
            ?>
        </span>
    </div>
</div>
<?php
$this->registerJs("
    $(document).ready(function(){
        //защита от повторных регистраций
        localStorage.setItem('register', 'zzz');
    });
    ");
?>

frontend/views/site/left.php
<?php
use yii\helpers\Url;
$current_action = Yii::$app->controller->action->id
?>
<div class="sidebar">
    <ul class="sidebar__nav">
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-support<?php echo $current_action == 'news' ? ' active-empty' : ''?>" href="<?= Url::to(['/site/news']) ?>">
                <span class="sidebar__title">Новости</span>
            </a>
        </li>
        <li class="sidebar__row">
            <a class="sidebar__item sidebar__item-profile<?php echo $current_action == 'signup' ? ' active-empty' : ''?>" href="<?= Url::to(['/site/signup']) ?>">
                <span class="sidebar__title">Регистрация</span>
            </a>
        </li>
    </ul>
    <a class="show-menu" href="#?">
        <span class="show-menu__ico"></span>
        <span class="show-menu__title">свернуть</span>
    </a>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Вход';
?>

<div style="font-size: 16px; font-weight: bold">
    Если это ваш первый вход в новый личный кабинет, то вам необходимо сбросить ваш пароль!
    <br> <?= Html::a('Сбросить пароль', ['site/request-password-reset']) ?>.
</div>
<br><br>

<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

<?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

<?= $form->field($model, 'password')->passwordInput() ?>

<?= $form->field($model, 'rememberMe')->checkbox() ?>

<div style="color:#999;margin:1em 0">
    Если вы забыли свой пароль, то можете <?= Html::a('сбросить его', ['site/request-password-reset']) ?>.
</div>

<div class="form-group">
    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
</div>

<?php ActiveForm::end(); ?>

frontend/views/site/news-single.php
<?php

/* @var $this yii\web\View */
/* @var $news object */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Новости';
$this->params['breadcrumbs'][] = ['label' => 'Все новости', 'url' => [Url::to(['site/news'])]];
$this->params['breadcrumbs'][] = $news->title;

?>

<div class="site-news">
    <div class="info__title"><?= Html::encode($news->title) ?></div>
    <p><?= Yii::$app->formatter->asDate($news->created_at) ?></p>
    <div class="info__text"><?= $news->content ?></div>
</div>

frontend/views/site/news.php
<?php
/* @var $this yii\web\View */
/* @var $listDataProvider object*/

use yii\widgets\ListView;

$this->title = 'Новости';

echo ListView::widget([
    'dataProvider' => $listDataProvider,
    'itemView' => '_list_news',
    'summary' => 'Показано {count} из {totalCount}',

]);

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Запрос на сброс пароля';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <p>Пожалуйста, заполните ваш адрес электронной почты. Ссылка для сброса пароля будет выслана на него.</p>
    <br>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Сброс пароля';
?>
<div class="site-reset-password">
    <p>Пожалуйста, выберите Ваш новый пароль:</p>
    <br>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/right.php
<?php
use frontend\widgets\NewsWidget;
use yii\helpers\Url;
?>
<div class="news">
    <span class="title-block">Наши новости</span>
    <ul class="news__list">
        <?php NewsWidget::begin(); ?>
        <li class="news__item">
            <div class="news__date">:date</div>
            <a class="news__title" href="<?= Url::to(['/site/news', 'id' => 'newsId']) ?>"><span>:title</span></a>
        </li>
        <?php NewsWidget::end(); ?>
    </ul>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <p class="info__text">Пожалуйста, заполните следующие поля для регистрации:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php
            $form = ActiveForm::begin(['id' => 'form-signup']); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'email') ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'local_storage')->hiddenInput(['id' => 'local_storage'])->label(false) ?>

            <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                'template' => '
                            <div class="row">
                                <div class="col-lg-6 captcha">{image}</div>
                                <div class="col-lg-6">{input}</div>
                            </div>',
                'captchaAction'=>'/site/captcha'
            ]) ?>
            <div class="form-group">
                <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php
    $this->registerJs("
    $(document).ready(function(){
        //защита от повторных регистраций
        var register = localStorage.getItem('register');
        if(register) {
            $('#local_storage').val(register);
        } else {
            $('#local_storage').val('ok');
        }
    });
    ");
?>